### ISSUE TITLE
Cant find the config file

### ISSUE THREAD

**Issue by ilQueen** [RedstoneDubstep/PlayerNameModifier#1]
I just installed the mod to my server and I cannot find the config file (1.20.6 Neoforge server)

**Comment by RedstoneDubstep** [comment]
Hello, thanks for notifying me! This is entirely my bad, I forgot to rename a file during the 1.20.6 updating process, and because of that, the mod doesn't even get recognized by Neoforge. Will re-upload the working file in the coming days.
