### ISSUE TITLE
Theres no Command or file to edit names

### ISSUE THREAD

**Issue by RADD95** [RedstoneDubstep/PlayerNameModifier#2]
im using the mod for forge 1.20.1 but theres no command or file to edit the names the only command i can use is refresplayernames and thats it

**Comment by RedstoneDubstep** [comment]
Hello, you can change the name modifier that should be applied to player names via the server configuration file of PlayerNameModifier (but you can only modify that when the server is offline, else the changes won't get accepted).

**Comment by RADD95** [comment]
Where's the configuration file supposed to be? There's no PlayerNameModifier file in the config folder or anything similar, so I don't really know what file I'm supposed to modify.

**Comment by RedstoneDubstep** [comment]
The file is supposed to be in the `world/serverconfig` folder in your server folder, and be called `playernamemodifier-server.toml`. If it isn't there, make sure the mod is in the mods folder of the server and gets recorgnized properly (you can check that by e.g. running the command `/forge mods` and look if PlayerNameModifier is listed)
